// Generated by IcedCoffeeScript 1.8.0-d
(function() {
  var bindSiteBtn, genURL, handleBaidu, handleGoogle, main, parseURL, searchUrlMapping, urlHandlers;

  parseURL = function(url) {
    var item, parser, queries, searchObject, split, _i, _len;
    if (url) {
      parser = document.createElement('a');
      parser.href = url;
    } else {
      parser = location;
    }
    searchObject = {};
    queries = parser.search.replace(/^\?/, '').split('&');
    for (_i = 0, _len = queries.length; _i < _len; _i++) {
      item = queries[_i];
      split = item.split('=');
      searchObject[split[0]] = split[1];
    }
    return {
      origin: parser.origin,
      protocol: parser.protocol,
      host: parser.host,
      hostname: parser.hostname,
      port: parser.port,
      pathname: parser.pathname,
      search: parser.search,
      searchObject: searchObject,
      hash: parser.hash
    };
  };

  genURL = function(url, pathname, searchObject) {
    var k, obj, search, ser, v;
    obj = parseURL(url);
    if (obj.pathname === pathname) {
      searchObject = $.extend({}, obj.searchObject || {}, searchObject || {});
    }
    search = "?";
    for (k in searchObject) {
      v = searchObject[k];
      ser = "" + k + "=" + (v || '');
      search += ser + '&';
    }
    search = search.replace(/[\?&]$/, '');
    return "" + obj.origin + "/" + obj.pathname + search;
  };

  bindSiteBtn = function(wrapNode, engine, onclick) {
    var btnTemplate, iconSrc, site;
    site = engine.split('_')[0];
    iconSrc = chrome.extension.getURL("icons/" + site + "48.png");
    btnTemplate = "<img class='SEI_web_search' data_site='" + site + "' title='" + site + "' src=\"" + iconSrc + "\" alt=\"" + site + "\">";
    wrapNode.append(btnTemplate);
    return $("img.SEI_web_search[data_site='" + site + "']").click(onclick);
  };

  handleBaidu = function(engines) {
    var engine, genClickFunc, wrapSel, _i, _len, _results;
    wrapSel = 'span.s_btn_wr, span.bdv-search-btns, span.input_span';
    $(wrapSel).hide();
    genClickFunc = function(engine) {
      return function() {
        var inputText;
        inputText = $("input[name='wd'], input[name='word']").val();
        return window.location.href = searchUrlMapping[engine] + inputText;
      };
    };
    _results = [];
    for (_i = 0, _len = engines.length; _i < _len; _i++) {
      engine = engines[_i];
      _results.push(bindSiteBtn($(wrapSel).parent(), engine, genClickFunc(engine)));
    }
    return _results;
  };

  handleGoogle = function(engines) {};

  urlHandlers = {
    '.*www.baidu.com\/s?': function() {
      return handleBaidu(['baidu', 'google']);
    },
    '.*news.baidu.com\/': function() {
      return handleBaidu(['baidu_news', 'google_news']);
    },
    '.*image.baidu.com\/': function() {
      return handleBaidu(['baidu_image', 'google_image']);
    },
    '.*v(ideo)?.baidu.com\/': function() {
      return handleBaidu(['baidu_video', 'google_video']);
    },
    '.*map.baidu.com\/': function() {
      return handleBaidu(['baidu_map', 'google_map']);
    }
  };

  searchUrlMapping = {
    'baidu': "http://www.baidu.com/s?wd=",
    'baidu_news': "http://news.baidu.com/ns?word=",
    'google': "https://www.google.com/search?q=",
    'google_news': 'https://www.google.com/search?tbm=nws&q=',
    'baidu_image': 'http://image.baidu.com/i?word=',
    'google_image': 'https://www.google.com/search?tbm=isch&q=',
    'baidu_video': 'http://v.baidu.com/v?word=',
    'google_video': 'https://www.google.com/search?tbm=vid&q=',
    'baidu_map': 'http://map.baidu.com/m?word=',
    'google_map': 'https://maps.google.com/maps?q='
  };

  main = function() {
    var handler, m;
    for (m in urlHandlers) {
      handler = urlHandlers[m];
      if (location.href.match(m)) {
        handler.call(this);
      }
    }
  };

  main();

}).call(this);
