// Generated by IcedCoffeeScript 1.8.0-d
(function() {
  var baiduWebMain, main, urlHandlers;

  baiduWebMain = function() {
    var btnTemplate, iconSrc, wrapSel;
    wrapSel = 'span.s_btn_wr';
    iconSrc = chrome.extension.getURL('icons/baidu48.png');
    btnTemplate = "<img class='SEI_web_search' data_site='site' src=\"" + iconSrc + "\" alt=\"baidu\">";
    $(wrapSel).empty();
    $(wrapSel).append(btnTemplate);
    return $('.SEI_web_search').click(function() {
      var inputText;
      inputText = $("input[name='wd']").val();
      return window.location.href = "http://www.baidu.com/s?wd=" + inputText;
    });
  };

  urlHandlers = {
    '.*www.baidu.com\/s?': baiduWebMain
  };

  main = function() {
    var handler, m;
    for (m in urlHandlers) {
      handler = urlHandlers[m];
      if (location.href.match(m)) {
        handler.call(this);
      }
    }
  };

  main();

}).call(this);
